package proyecto;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ricky
 */

public class menu extends javax.swing.JFrame {
DefaultTableModel modelo;
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        modelo=(DefaultTableModel)jTable1.getModel();      
        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setName(""); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ricardo", "Kevin", "Sergio" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cliente", "prestamo", "monto"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 319, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Clientes");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cuentas");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Empleados");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Estados");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu4MousePressed(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Municipios");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu5MousePressed(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Prestamos");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu6MousePressed(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
         Clientes ej=new Clientes();
       ej.show(); // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MousePressed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
  Clientes ej=new Clientes();
       ej.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
 Cuentas ej=new Cuentas();
       ej.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
 Empleados ej=new Empleados();
       ej.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
       Estados ej=new Estados();
       ej.show(); // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
Municipios ej=new Municipios();
       ej.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
Prestamos ej=new Prestamos();
       ej.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
 Cuentas ej=new Cuentas();
       ej.show();         // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MousePressed

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
Empleados ej=new Empleados();
       ej.show();         // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MousePressed

    private void jMenu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MousePressed
 Estados ej=new Estados();
       ej.show();         // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MousePressed

    private void jMenu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MousePressed
 Municipios ej=new Municipios();
       ej.show();         // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MousePressed

    private void jMenu6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MousePressed
 Prestamos ej=new Prestamos();
       ej.show();         // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6MousePressed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
cargar();        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                La_Palma lp=new La_Palma();
       lp.show(); 
                //new menu().setVisible(true);
            }
        });
    }
public void cargar(){
         modelo.setRowCount(0);
         modelo.setColumnCount(0);
        try {
            MySql bd = new MySql();
            String c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12;
            //creamos la conexion
            bd.MySqlConnect();
            //Tabla
            String nomTabla = "";
            //estalbecemos la consulta
            String Query = "";
            switch(jComboBox1.getSelectedIndex()){
                case 0:
                    modelo.addColumn("cliente");
                    modelo.addColumn("monto");
                    modelo.addColumn("Plazo_meses");
                    modelo.addColumn("Num_prestamo");
                    modelo.addColumn("Abono");
                    nomTabla="prestamos";
                    Query="select c.nombre, p.monto , p.plazo_meses, p.num_prestamo ,(p.monto/p.plazo_meses)as abono from  clientes c join prestamos p where p.id_clientes=c.id_clientes;";
                     bd.comando = bd.conexion.createStatement();
            bd.registro=bd.comando.executeQuery(Query);
            //Imprimir cada uno de los registros que estan en la BD
            while(bd.registro.next()){
                c1=bd.registro.getString(1).toString();
                c2=bd.registro.getString(2).toString();
                c3=bd.registro.getString(3).toString();
                c4=bd.registro.getString(4).toString();
                c5=bd.registro.getString(5).toString();
                Object model[]=new Object[]{c1,c2,c3,c4,c5};
                modelo.addRow(model);
            }
                    break;
                case 1:
                       modelo.addColumn("id_municipios");
                    modelo.addColumn("nombre");
                    modelo.addColumn("empleados");
                    nomTabla="prestamos";
                    Query="select m.id_municipios, m.nombre, count(e.id_empleados) from municipios m join "
                            + "empleados e on m.id_municipios=e.id_municipios group by m.id_municipios;";
                     bd.comando = bd.conexion.createStatement();
            bd.registro=bd.comando.executeQuery(Query);
            //Imprimir cada uno de los registros que estan en la BD
            while(bd.registro.next()){
                c1=bd.registro.getString(1).toString();
                c2=bd.registro.getString(2).toString();
                c3=bd.registro.getString(3).toString(); 
                Object model[]=new Object[]{c1,c2,c3};
                modelo.addRow(model);
            }
                    break;
                case 2:
                       modelo.addColumn("id");
                       modelo.addColumn("nombre");
                       modelo.addColumn("ap_pat");
                       modelo.addColumn("ap_mat");
                       modelo.addColumn("dom");
                       modelo.addColumn("fecha_n");
                       modelo.addColumn("id_mun");
                       modelo.addColumn("correo");
                       modelo.addColumn("tel");
                       modelo.addColumn("sexo");
                       modelo.addColumn("estado");
                       modelo.addColumn("oficio");
                    nomTabla="prestamos";
                    Query="select c.* from clientes c join prestamos p on p.id_clientes=c.id_clientes where monto>(select monto from prestamos where id_clientes=(select id_clientes from clientes where nombre='juan'));";
                     bd.comando = bd.conexion.createStatement();
            bd.registro=bd.comando.executeQuery(Query);
            //Imprimir cada uno de los registros que estan en la BD
            while(bd.registro.next()){
                c1=bd.registro.getString(1).toString();
                c2=bd.registro.getString(2).toString();
                c3=bd.registro.getString(3).toString();
                c4=bd.registro.getString(4).toString();
                c5=bd.registro.getString(5).toString();
                c6=bd.registro.getString(6).toString();
                c7=bd.registro.getString(7).toString();
                c8=bd.registro.getString(8).toString();
                c9=bd.registro.getString(9).toString();
                c10=bd.registro.getString(10).toString();
                c11=bd.registro.getString(11).toString();
                c12=bd.registro.getString(12).toString();
                Object model[]=new Object[]{c1,c2,c3,c4,c5,c6,c7,c8,c9, c10,c11,c12};
                modelo.addRow(model);
            }    
                    break;
            }
            //se crea la sentencia, y se ejecuta
           
        }catch(SQLException e){
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
